function out1 = jacob_right_s_y_cam0(X,Y,fy,ptx,pty,ptz,pwx,pwy,pwz,py,rs2_1,rs2_2,rs2_3,rs3_1,rs3_2,rs3_3,s,ts2,ts3)
%JACOB_RIGHT_S_Y_CAM0
%    OUT1 = JACOB_RIGHT_S_Y_CAM0(X,Y,FY,PTX,PTY,PTZ,PWX,PWY,PWZ,PY,RS2_1,RS2_2,RS2_3,RS3_1,RS3_2,RS3_3,S,TS2,TS3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    28-Nov-2018 10:39:59

t2 = pwx.^2;
t3 = pwy.^2;
t4 = pwz.^2;
t5 = t2+t3+t4;
t6 = sqrt(t5);
t7 = sin(t6);
t8 = 1.0./sqrt(t5);
t9 = cos(t6);
t10 = t9-1.0;
t11 = 1.0./t5;
t12 = pwz.*t7.*t8;
t13 = ptx.*rs3_1;
t14 = pty.*rs3_2;
t15 = ptz.*rs3_3;
t16 = t13+t14+t15+ts3;
t17 = 1.0./s.^2;
t18 = pwx.*pwy.*t10.*t11;
t19 = pwy.*t7.*t8;
t20 = pwx.*pwz.*t10.*t11;
t21 = t19+t20;
t22 = t3+t4;
t23 = t10.*t11.*t22;
t24 = t23+1.0;
t25 = rs3_1.*t24;
t26 = t12+t18;
t27 = pwx.*t7.*t8;
t48 = pwy.*pwz.*t10.*t11;
t28 = t27-t48;
t29 = rs3_3.*t28;
t30 = t2+t4;
t31 = t10.*t11.*t30;
t32 = t31+1.0;
t33 = rs3_2.*t32;
t49 = rs3_1.*t26;
t34 = t29+t33-t49;
t35 = Y.*t34;
t36 = 1.0./s;
t37 = t16.*t36;
t38 = ptx.*rs2_1;
t39 = pty.*rs2_2;
t40 = ptz.*rs2_3;
t41 = t38+t39+t40+ts2;
t42 = fy.*t41;
t43 = py.*t16;
t44 = t42+t43;
t45 = t12-t18;
t46 = rs3_2.*t45;
t47 = t25+t46-rs3_3.*t21;
out1 = (t17.*t44)./(t35+t37+X.*(t25-rs3_3.*t21+rs3_2.*(t12-pwx.*pwy.*t10.*t11)))-t16.*t17.*(t36.*t44+X.*(py.*t47+fy.*(-rs2_3.*t21+rs2_1.*t24+rs2_2.*t45))+Y.*(py.*t34+fy.*(-rs2_1.*t26+rs2_3.*t28+rs2_2.*t32))).*1.0./(t35+t37+X.*t47).^2;
