function ey = ey_BA(R2_1,R2_2,R2_3,R3_1,R3_2,R3_3,X,Y,Z,fy,py,t2,t3,tx,ty,tz,wx,wy,wz,y)
%EY_BA
%    EY = EY_BA(R2_1,R2_2,R2_3,R3_1,R3_2,R3_3,X,Y,Z,FY,PY,T2,T3,TX,TY,TZ,WX,WY,WZ,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Feb-2019 12:25:32

t4 = wx.^2;
t5 = wy.^2;
t6 = wz.^2;
t7 = t4+t5+t6;
t8 = sqrt(t7);
t9 = sin(t8);
t10 = 1.0./sqrt(t7);
t11 = cos(t8);
t12 = t11-1.0;
t13 = 1.0./t7;
t14 = t9.*t10.*wz;
t22 = t12.*t13.*wx.*wy;
t15 = t14-t22;
t16 = t9.*t10.*wy;
t17 = t12.*t13.*wx.*wz;
t18 = t16+t17;
t19 = t5+t6;
t20 = t12.*t13.*t19;
t21 = t20+1.0;
t23 = t14+t22;
t24 = t9.*t10.*wx;
t29 = t12.*t13.*wy.*wz;
t25 = t24-t29;
t26 = t4+t6;
t27 = t12.*t13.*t26;
t28 = t27+1.0;
t30 = t16-t17;
t31 = t24+t29;
t32 = t4+t5;
t33 = t12.*t13.*t32;
t34 = t33+1.0;
t35 = R3_1.*tx;
t36 = R3_2.*ty;
t37 = R3_3.*tz;
t38 = R3_2.*t15;
t39 = R3_1.*t21;
t40 = t38+t39-R3_3.*t18;
t41 = R3_3.*t25;
t42 = R3_2.*t28;
t43 = t41+t42-R3_1.*t23;
t44 = R3_1.*t30;
t45 = R3_3.*t34;
t46 = t44+t45-R3_2.*t31;
ey = y-(fy.*(t2+R2_1.*tx+R2_2.*ty+R2_3.*tz)+X.*(py.*t40+fy.*(R2_2.*t15-R2_3.*t18+R2_1.*t21))+Y.*(py.*t43+fy.*(-R2_1.*t23+R2_3.*t25+R2_2.*t28))+Z.*(py.*t46+fy.*(R2_1.*t30-R2_2.*t31+R2_3.*t34))+py.*(t3+t35+t36+t37))./(t3+t35+t36+t37+X.*t40+Y.*t43+Z.*t46);
