function err_sym_y = err_fun_y_(Ri2_1,Ri2_2,Ri2_3,Ri3_1,Ri3_2,Ri3_3,X,Y,Z,fy,py,ti2,ti3,tx,ty,tz,wx,wy,wz,y)
%ERR_FUN_Y_
%    ERR_SYM_Y = ERR_FUN_Y_(RI2_1,RI2_2,RI2_3,RI3_1,RI3_2,RI3_3,X,Y,Z,FY,PY,TI2,TI3,TX,TY,TZ,WX,WY,WZ,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Jan-2019 12:39:02

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3+t4;
t6 = sqrt(t5);
t7 = sin(t6);
t8 = 1.0./sqrt(t5);
t9 = cos(t6);
t10 = t9-1.0;
t11 = 1.0./t5;
t12 = t7.*t8.*wz;
t20 = t10.*t11.*wx.*wy;
t13 = t12-t20;
t14 = t7.*t8.*wy;
t15 = t10.*t11.*wx.*wz;
t16 = t14+t15;
t17 = t3+t4;
t18 = t10.*t11.*t17;
t19 = t18+1.0;
t21 = t12+t20;
t22 = t7.*t8.*wx;
t27 = t10.*t11.*wy.*wz;
t23 = t22-t27;
t24 = t2+t4;
t25 = t10.*t11.*t24;
t26 = t25+1.0;
t28 = t14-t15;
t29 = t22+t27;
t30 = t2+t3;
t31 = t10.*t11.*t30;
t32 = t31+1.0;
t33 = Ri3_1.*tx;
t34 = Ri3_2.*ty;
t35 = Ri3_3.*tz;
t36 = Ri3_2.*t13;
t37 = Ri3_1.*t19;
t38 = t36+t37-Ri3_3.*t16;
t39 = Ri3_3.*t23;
t40 = Ri3_2.*t26;
t41 = t39+t40-Ri3_1.*t21;
t42 = Ri3_1.*t28;
t43 = Ri3_3.*t32;
t44 = t42+t43-Ri3_2.*t29;
err_sym_y = y-(fy.*(ti2+Ri2_1.*tx+Ri2_2.*ty+Ri2_3.*tz)+X.*(py.*t38+fy.*(Ri2_2.*t13-Ri2_3.*t16+Ri2_1.*t19))+Y.*(py.*t41+fy.*(-Ri2_1.*t21+Ri2_3.*t23+Ri2_2.*t26))+Z.*(py.*t44+fy.*(Ri2_1.*t28-Ri2_2.*t29+Ri2_3.*t32))+py.*(t33+t34+t35+ti3))./(t33+t34+t35+ti3+X.*t38+Y.*t41+Z.*t44);
