function err_sym_x = err_fun_x_(Ri1_1,Ri1_2,Ri1_3,Ri3_1,Ri3_2,Ri3_3,X,Y,Z,fx,px,ti1,ti3,tx,ty,tz,wx,wy,wz,x)
%ERR_FUN_X_
%    ERR_SYM_X = ERR_FUN_X_(RI1_1,RI1_2,RI1_3,RI3_1,RI3_2,RI3_3,X,Y,Z,FX,PX,TI1,TI3,TX,TY,TZ,WX,WY,WZ,X)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Jan-2019 12:39:01

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3+t4;
t6 = sqrt(t5);
t7 = sin(t6);
t8 = 1.0./sqrt(t5);
t9 = cos(t6);
t10 = t9-1.0;
t11 = 1.0./t5;
t12 = t7.*t8.*wz;
t20 = t10.*t11.*wx.*wy;
t13 = t12-t20;
t14 = t7.*t8.*wy;
t15 = t10.*t11.*wx.*wz;
t16 = t14+t15;
t17 = t3+t4;
t18 = t10.*t11.*t17;
t19 = t18+1.0;
t21 = t12+t20;
t22 = t7.*t8.*wx;
t27 = t10.*t11.*wy.*wz;
t23 = t22-t27;
t24 = t2+t4;
t25 = t10.*t11.*t24;
t26 = t25+1.0;
t28 = t14-t15;
t29 = t22+t27;
t30 = t2+t3;
t31 = t10.*t11.*t30;
t32 = t31+1.0;
t33 = Ri3_1.*tx;
t34 = Ri3_2.*ty;
t35 = Ri3_3.*tz;
t36 = Ri3_2.*t13;
t37 = Ri3_1.*t19;
t38 = t36+t37-Ri3_3.*t16;
t39 = Ri3_3.*t23;
t40 = Ri3_2.*t26;
t41 = t39+t40-Ri3_1.*t21;
t42 = Ri3_1.*t28;
t43 = Ri3_3.*t32;
t44 = t42+t43-Ri3_2.*t29;
err_sym_x = x-(fx.*(ti1+Ri1_1.*tx+Ri1_2.*ty+Ri1_3.*tz)+X.*(px.*t38+fx.*(Ri1_2.*t13-Ri1_3.*t16+Ri1_1.*t19))+Y.*(px.*t41+fx.*(-Ri1_1.*t21+Ri1_3.*t23+Ri1_2.*t26))+Z.*(px.*t44+fx.*(Ri1_1.*t28-Ri1_2.*t29+Ri1_3.*t32))+px.*(t33+t34+t35+ti3))./(t33+t34+t35+ti3+X.*t38+Y.*t41+Z.*t44);
